# Create custom nginx if not found, buildup and running

version: '2'
services: 
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
    image: customnginx
    ports: 
      - "8080:80"
    volumes: 
      - ./website:/usr/share/nginx/html
