# create your drupal and postgres config here, based off the last assignment
version: '2'

services:

  drupal:
    image: drupal
    ports:
            - "8080:80"
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/sites
    restart: always

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: always
